### ISSUE TITLE
too many heart beat logs

### ISSUE THREAD

**Issue by collinmsn** [nsqio/pynsq#119]
```python
   def _on_heartbeat(self, conn):
        logger.info('[%s:%s] received heartbeat' % (conn.id, self.name))
        self.heartbeat(conn)
```

This produces too many logs. Set the log level to debug?

**Comment by mreiferson** [comment]
have you lowered `heartbeat_interval`?

I'm inclined to leave this alone as I believe there is value in being able to confirm your consumer is receiving heartbeats by default, but we could move the logging statement to inside `heartbeat()` (which is the method that is expected to be overwritten and implemented by the user).

**Comment by haroldTlan** [comment]
Could you tell me how to use the heartbeat() ?

**Comment by ploxiln** [comment]
This works for me:

```python
logging.getLogger('nsq').setLevel(logging.WARNING)
```

**Comment by doron2402** [comment]
thanks @ploxiln
