### ISSUE TITLE
can i use pynsq writer directly without tornado?

### ISSUE THREAD

**Issue by zheng-ji** [nsqio/pynsq#137]
can i use pynsq writer to pub message directory without tornado callback

i try to use like that

```
writer.pub('test_topic','helloworld')
```

but it failed and said no logger found 'nsq.writer'

**Comment by mreiferson** [comment]
Can you paste the actual error output?

**Comment by zheng-ji** [comment]
Thanks for your concern:)

Here is my code:

```
import nsq
writer = nsq.Writer(['127.0.0.1:4150'])
writer.pub("test_topic", "hello world")
```

its output 

```
No handlers could be found for logger "nsq.writer"
```

and It can not pub the "helle world" message to the nsqd 
my purpose is to pub message to nsqd directly without tornado IOLoop or tornado web handler

Thanks for your help!

**Comment by ploxiln** [comment]
You need to initialize the python logging system to avoid that error. You can add this code to do that:

```
import logging
logging.basicConfig(level=logging.INFO)
```

But that just enables nsq to log an error; it needs a running tornado ioloop to work.

> I don't want to use http method

HTTP is the simplest and most flexible way to publish to nsq (and access a variety of APIs) from whatever application / context you have - there's an http client for every context. It's going to be way easier than forcing nsq.writer to work without a running tornado ioloop.

I am able to use nsq.writer without a *long term* tornado ioloop, but this is terrible and you should not do this:

```
import logging
import nsq
import tornado
logging.basicConfig(level=logging.INFO)

writer = nsq.Writer(['127.0.0.1:4150'])

@tornado.gen.coroutine
def do_pub():
    yield tornado.gen.sleep(1)
    writer.pub("test_topic", "hello world")
    yield tornado.gen.sleep(1)

tornado.ioloop.IOLoop.instance().run_sync(do_pub)
print("wrote one message to nsq")
tornado.ioloop.IOLoop.instance().run_sync(do_pub)
print("wrote another message to nsq")
```

use http
