### ISSUE TITLE
Confuse with using nsqd

### ISSUE THREAD

**Issue by zheng-ji** [nsqio/pynsq#138]
Thanks for your time.

### Question 1:
I have a worry about using nsqd.

I have two nsqd register the same lookupd_tcp_address(127.0.0.1:4160)
they are:

```
nsqd-1: http-address is 127.0.0.1:4151
nsqd-2: http-address is 127.0.0.1:4153
```

I publish a message `helloworld` to nsqd-1 (127.0.0.1:4151) using

```
curl curl -d 'hello world' 'http://127.0.0.1:4151/pub?topic=test
```

If something wrong with nsqd-1, and it was killed, what should i do to  avoid single point failure.
Actually,i don't know  whether nsqd-2 could replace nsqd-1 at that time without changing my code.

### Question 2:
If i use http as a way to publish message in productive environment , should i worry about the overhead of http.

Thanks Sincerely

**Comment by mreiferson** [comment]
First, these kinds of questions are better off on the [mailing list](https://groups.google.com/forum/#!forum/nsq-users).

Q1: NSQ has no build in replication and `nsqd` do not coordinate so there isn't any built in mechanism to ensure that more than one node has the messages you're publishing.  You can dual-publish on the application side.

Q2: No, the convenience of HTTP outweighs the overhead which can also be minimized in high-volume scenarios by using `/mpub`.
