### ISSUE TITLE
support DPUB

### ISSUE THREAD

**Issue by iameugenejo** [nsqio/pynsq#139]
This feature has been out since 0.3.6 (Sept 25, 2015) and I see this implemented in go client, but not in python one.

Any plan for supporting dpub? 

reference - https://github.com/nsqio/go-nsq/blob/37e5a55ed8546a1954c0dccf4e44a48e67db931b/command.go#L136-L141

**Comment by mreiferson** [comment]
done in #140

**Comment by iameugenejo** [comment]
awesome, thanks!
