### ISSUE TITLE
reader: allow infinite attempts

### ISSUE THREAD

**Issue by iameugenejo** [nsqio/pynsq#142]
We have a situation where we do not want to lose messages at all for a certain topic.

Can we allow setting "max_try" of Reader to 0 or non-positive and consider the value as indefinite attempts, so the message never gets silently discarded automatically?

I can send a PR for it if that's a feature that many people may seek. (I figured some 3rd party client implementation that does this btw.)

**Comment by iameugenejo** [comment]
I found that go client has it - https://github.com/nsqio/go-nsq/blob/master/consumer.go#L1128

**Comment by mreiferson** [comment]
sure, seems reasonable, send a PR!

**Comment by mreiferson** [comment]
see #144
