### ISSUE TITLE
Allow pause and resume Reader

### ISSUE THREAD

**Issue by iameugenejo** [nsqio/pynsq#143]
I found a go client implementation it, but not in python client - https://github.com/nsqio/go-nsq/blob/master/consumer.go#L817-L855

I'll send a PR for it in a moment.

**Comment by mreiferson** [comment]
:+1:

**Comment by iameugenejo** [comment]
Please ignore the first two commits, I overwrote my own changes from another PR and didn't know until I pushed the new changes (did that twice), and deleted the branch thinking it would clear up the history. I guess github keep tracks of forked repositories' branches.

**Comment by mreiferson** [comment]
https://github.com/nsqio/pynsq/pull/145#issuecomment-180464576
