### ISSUE TITLE
Connection is stale while waiting for message

### ISSUE THREAD

**Issue by monhz** [nsqio/pynsq#151]
For my Message handler need quit a long time to process, I enable the message asynchronously as follows:
```
def handler(message):
    message.enable_async()
    # process it for a long time
    deal_with_task()
    message.finish()
```
and my nsq reader set like this
```
nsq.Reader(
    message_handler=self.handler,
    lookupd_http_addresses=NSQ_LOOKUP_HOST,
    channel=LISTEN_CHANNEL,
    topic=LISTEN_TOPIC,
    lookupd_poll_interval=100,
    msg_timeout=3600,
    max_tries=3,
    max_in_flight=1,
)
nsq.run()
```

The program may get the error like this in some cases:
```
WARNING:nsq.client:[127.0.0.1:4152] connection is stale (298.42s), closing
ERROR:nsq.async:uncaught exception in data event
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nsq/async.py", line 275, in _read_body
    self.trigger(event.DATA, conn=self, data=data)
  File "/usr/local/lib/python2.7/site-packages/nsq/event.py", line 85, in trigger
    ev(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/nsq/async.py", line 477, in _on_data
    self.send(protocol.nop())
  File "/usr/local/lib/python2.7/site-packages/nsq/async.py", line 281, in send
    self.stream.write(data)
  File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 377, in write
    self._check_closed()
  File "/usr/local/lib/python2.7/site-packages/tornado/iostream.py", line 885, in _check_closed
    raise StreamClosedError(real_error=self.error)
StreamClosedError: Stream is closed
```

I don't know what's wrong with the program. And I am sure that there is no error uncaught while processing the task. The error happens when nsq client is listening on the nsqd.
If anyone needs more codes, I can paste here.

**Comment by mreiferson** [comment]
You can't block the IOLoop while you're processing the message because `pynsq` won't be able to reply to heartbeats, that's why the connection is being closed.

You've got to figure out a way to perform that work asynchronously.

**Comment by monhz** [comment]
Thanks for your reply.
You said that I have to perform the work asynchronous. I am wondering whether the multiprocessing threads is the only solution to the problem in one process.
I am really not so skilled in unblocked programming, I hope you can help me.

**Comment by cyuxlif** [comment]
same question

**Comment by g8gg** [comment]
same question (nsq v1.0.0 pynsq 0.8.0

**Comment by mreiferson** [comment]
Yes, threads are one way to achieve this, e.g. using [Tornado's `ThreadPoolExecutor`](http://www.tornadoweb.org/en/stable/guide/coroutines.html#calling-blocking-functions)

**Comment by alpaker** [comment]
> So,if I want to use 121 seconds to do my job,and I set the msg-message="120s".The nsqd also force to requeue the message,does it mean I should set the msg-message>121 seconds?

Yes.  The argument to pass to to `nsq.Reader()` is `msg_timeout`.

> By the way,do i use the message.enable_async() in a correct way?

Yes, except for where you're invoking `finish()`. In general it's not safe to a call a method that interacts with a Tornado IO loop (as `finish()` does) from a thread other the thread that IO loop is running on (in this case, the thread the `Reader` is running on).

You don't want to use Python threads directly, but rather via a tornado executor facilities.  An example is [here](https://gist.github.com/methane/2185380).  You'll want to invoke `finish()` in the callback you pass to `run_background()`.

**Comment by patterson163** [comment]
@alpaker  Thanks for reply.
