### ISSUE TITLE
Could you provide a example writer with all interact with tornado?

### ISSUE THREAD

**Issue by hicqu** [nsqio/pynsq#152]
Hi everybody, I am learning tornado now and I need a service which can does this:
The service will read  message from a python thread-safe queue, and then write them into a Writer.
So how to implement that?
Please help me, Thanks a lot!
Here is a try, but it didn't work.
```
#!/usr/bin/env python2
# coding=utf-8

import tornado
import time
from nsq.writer import Writer

w = Writer(["bj1:4150", "bj2:4150"], reconnect_interval=15)
w.connect()


@tornado.gen.coroutine
def future_pub(topic, msg):
    result = w.pub(topic, msg)
    print(result)
    time.sleep(3)
    raise tornado.gen.Return(result)


@tornado.gen.coroutine
def main():
    while True:
        try:
            future = future_pub("test", "message")
            yield future
        except Exception as e:
            print(e.message)


tornado.ioloop.IOLoop.instance().run_sync(main)

```

**Comment by ploxiln** [comment]
see #137 

btw `time.sleep()` should not be used in a tornado coroutine or callback because it blocks

**Comment by hicqu** [comment]
Ok, thank you @ploxiln. As that issue recommanded, I will first implement my function with http-get method. Thanks!

**Comment by aohan237** [comment]
may you want to try asyncnsq
