### ISSUE TITLE
how to use channel

### ISSUE THREAD

**Issue by songlong** [nsqio/pynsq#153]
example:  curl -X POST http://127.0.0.1:4151/channel/create?topic=name&channel=nam
but I can not find api ??

**Comment by jehiah** [comment]
@songlong can you explain what you are trying to accomplish so we can best help?

**Comment by songlong** [comment]
how to use api about channels in pynsq?
when I create a topic, I want to create channels, but I can not find api interface.
under this topic, I can not use channels to multiple realize compute by user-defined method
