### ISSUE TITLE
Enforce messages published to be of type bytes

### ISSUE THREAD

**Issue by ghost** [nsqio/pynsq#154]
The Python client doesn't sanitize input as far as I can tell, in that if I pass it something that's not serialized to bytes, the client doesn't fail hard. I've had to pickle Python objects or json serialize them to publish to NSQ, but publishing works even when I try to pass it a dict. It then fails at the consumer side.

It's help if the client raise a TypeError if the what's being stored in `message.body`. Or there might already exist a resolution for this - but the docs don't make it very clear. I'm not sure what the right approach here would be, but I'd be happy to submit a PR for either a docs update or a fix to the library if needed.

Thanks!

**Comment by mreiferson** [comment]
Hi @copyconstructor - I'm a little confused because I would expect the client to fail loudly, see: https://github.com/nsqio/pynsq/blob/master/nsq/protocol.py#L73

Do you happen to be running without assertions turned on?

**Comment by ploxiln** [comment]
closing due to long time with no response
