### ISSUE TITLE
Recent Version

### ISSUE THREAD

**Issue by cathalgarvey** [nsqio/pynsq#165]
Is this still only compatible with Python 2, or has it been updated to work with a recent version?

Thanks!

**Comment by cathalgarvey** [comment]
Not trying to be lazy btw, I'm referring to the official metadata in `setup.py` which specifies Py2 only.

**Comment by ploxiln** [comment]
Yes this is compatible with Python 3 since [v0.7.0](https://github.com/nsqio/pynsq/releases/tag/v0.7.0) - but there have also been some small fixes for Python 3 since that release, #160 and #161

**Comment by cathalgarvey** [comment]
Great news, thanks!

Closes #165

On 16 December 2016 17:17:35 GMT+00:00, Pierce Lopez <notifications@github.com> wrote:
>Yes this is compatible with Python 3 since
>[v0.7.0](https://github.com/nsqio/pynsq/releases/tag/v0.7.0) - but
>there have also been some small fixes for Python 3 since that release,
>#160 and #161
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nsqio/pynsq/issues/165#issuecomment-267645548

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mreiferson** [comment]
just released v0.7.1!
