### ISSUE TITLE
Assertion error when using

### ISSUE THREAD

**Issue by morenoh149** [nsqio/pynsq#173]
I get the following
```
python queuereader.py 
Traceback (most recent call last):
  File "queuereader.py", line 56, in <module>
    max_tries=5
  File "/usr/local/lib/python2.7/site-packages/nsq/reader.py", line 188, in __init__
    assert nsqd_tcp_addresses or lookupd_http_addresses
AssertionError
```
trying to run https://gist.github.com/akellehe/39fba6eeb112df66c0f9375d19d200c4

**Comment by jehiah** [comment]
that gist has 

```
'nsq_lookupd_http_addresses': '',
```

Are you running with that value filled in?

**Comment by mreiferson** [comment]
Don't think this is an actionable bug, so I'm gonna close, but let us know if you have any other issues @morenoh149
