### ISSUE TITLE
Request for PyPI update

### ISSUE THREAD

**Issue by protoss-player** [nsqio/pynsq#180]
There were a couple of fixes for annoying issues since 0.8.0 (connection selection & RDY bookkeeping).
Could PyPI version be updated to incorporate those?

Thanks.

**Comment by mreiferson** [comment]
https://github.com/nsqio/pynsq/releases/tag/v0.8.1

**Comment by protoss-player** [comment]
Hi @mreiferson ,

I've just tried installing 0.8.1, and `pip` said:
```
No matching distribution found for pynsq==0.8.1
```

It seems like PyPI does not have any downloadables associated with the package, as there's no "File" section in the [v0.8.1 listing](https://pypi.python.org/pypi/pynsq) as opposed to [v0.8.0](https://pypi.python.org/pypi/pynsq/0.8.0).

**Comment by mreiferson** [comment]
fixed, sorry, thanks for the heads up!
