### ISSUE TITLE
reader: support coroutine for message_handler

### ISSUE THREAD

**Issue by ploxiln** [nsqio/pynsq#186]
according to https://groups.google.com/d/msg/python-tornado/7JNWKwCTvZs/LWejJcQpAwAJ

(In Tornado 5.0 ...) "I'll be deprecating the `callback` arguments throughout the codebase in favor of coroutine-style usage"

So, I think we should probably support using a coroutine for a Reader's `message_handler`.

**Comment by ploxiln** [comment]
... although, I admit, it is easy enough to `msg.enable_async()` and then `IOloop.current().add_callback(my_coroutine, msg)`

**Comment by mreiferson** [comment]
Yea, I'm +1 to this.

**Comment by soar** [comment]
Need this

**Comment by penfree** [comment]
> ... although, I admit, it is easy enough to `msg.enable_async()` and then `IOLoop.current().add_callback(my_coroutine, msg)`

but i want to batch send the msg to elasticsearch, batch index and index one by one has great performance difference

**Comment by ploxiln** [comment]
optimistically closing this in favor of #244
