### ISSUE TITLE
best practice for starting consumers for each topic

### ISSUE THREAD

**Issue by aravindhb** [nsqio/pynsq#197]
I am new to python and nsq and I am trying to implement nsq consumers for different topics for our application. The way I am designing this is to have a separate process for each topic. And, for each process, have several instances of Reader instantiated. Something like this:

        consumers = [test_consumer1, test_consumer2, .., ..]
        pool_size = len(consumers)
        pool = mp.Pool(pool_size)

        try:
            for consumer in consumers:
                pool.apply_async(consumer)

       def test_consumer():
          for i in range(5):
                 Reader(
                    topic=self.topic,
                    channel=self.channel,
                    message_handler=self.message_handler,
                    max_in_flight=5,
                    lookupd_http_addresses=self.lookupd_http_addresses
                )  
          nsq.run()

The reasoning behind this is to have one IOLoop instance and and 5 different reader instances for each process. This way I can have the processes running independently for each topic and scale better when I want to increase the number of consumers. Please let me know if there is a different/efficient way of doing this.

Thanks

**Comment by ploxiln** [comment]
This is the kind of thing to ask on the mailing-list.

One quick tip: there's no point in having multiple readers of the same topic/channel using the same event loop, it's equivalent to one reader with the sum of all max_in_flight (25 in this case), but has less efficient "RDY count" management.

**Comment by ploxiln** [comment]
I should have included the mailing-list link: https://groups.google.com/d/forum/nsq-users
