### ISSUE TITLE
Bug: "Import Error _DEFAULT_CA_CERTS" With tornado 5.0

### ISSUE THREAD

**Issue by tomzhu6066** [nsqio/pynsq#203]
Since tornado updated to 5.0, the latest version of pynsq has conflict with this new tornado:

```
>>> import nsq
Traceback (most recent call last):
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/nsq/async.py", line 31, in <module>
    from tornado.simple_httpclient import _default_ca_certs as default_ca_certs
ImportError: cannot import name '_default_ca_certs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/nsq/__init__.py", line 29, in <module>
    from .async import AsyncConn
  File "/Users/tom/Virtualenvs/athena/lib/python3.5/site-packages/nsq/async.py", line 34, in <module>
    from tornado.simple_httpclient import _DEFAULT_CA_CERTS
ImportError: cannot import name '_DEFAULT_CA_CERTS'
```

This bug causes huge consequences on my application and plz fix this ASAP.
Currently my way to fix this bug is to put these lines in requirements.txt to force tornado use 4.5.3:
```
tornado==4.5.3
pynsq
```

**Comment by tomzhu6066** [comment]
oooops I just found out pynsq-0.8.3 fixed that issue. ORZ.. waiting for this release!

**Comment by ploxiln** [comment]
Yup, still, this is a good additional note for #185

**Comment by kimixsx** [comment]
Encountered this issue + 1, where did you find out pynsq-0.8.3 fixed it?

**Comment by ploxiln** [comment]
the change in pynsq-0.8.3 is to require tornado < 5.0

**Comment by tomzhu6066** [comment]
@ploxiln yeah I checked the changes hahaha...

**Comment by yxy** [comment]
same issue

**Comment by memotype** [comment]
What is the status on this issue. Is there a workaround? I just ran "pip3 install pynsq" and trying to import it I get this error. Seems odd that this issue would still be open 6 months later being as it renders the module completely unusable...

**Comment by ploxiln** [comment]
This module is usable if you use tornado < 5.0
(which would be enforced by https://github.com/nsqio/pynsq/blob/master/setup.py#L35 but there has not yet been a pynsq release with that constraint). I suggest you `pip3 install tornado==4.5.3`

**Comment by ploxiln** [comment]
The setup.py checks for `tornado<5.0` but we haven't made any release since that change. There have also been a couple of python3-related fixes since then, so maybe it's time for another release @jehiah @mreiferson ?

(even though the long-awaited tornado-5.0 compatibility, which I said I would work on, has not been done yet ...)

**Comment by mreiferson** [comment]
Given that actual compatibility is a ways off, yea, should probably issue a point release for the patch.

**Comment by SylphiaWindy** [comment]
Why closed this while not fixed?

**Comment by hustliuxiao** [comment]
what's the time of next release of pynsq, i want to use pynsq  with tornado 5.1

**Comment by pirm-in** [comment]
Hi there! Is there any update about the support for tornado 5? compatibility with the asyncio loop would be awesome. maybe a feature branch where we could help?

or is there any other way to use pynsq, when i already have asyncio in place. i am currently struggling with combining the two, because i already have a forver-blocking loop.
Thanks!

**Comment by mreiferson** [comment]
please continue discussion in #185
