### ISSUE TITLE
writer SendError: no open connections following the examples in the documentation.

### ISSUE THREAD

**Issue by james-lawrence** [nsqio/pynsq#204]
there isn't a good example to connect to NSQ, deliver a bunch of work and then shutting down. seeing a bunch of race conditions due to the async nature of the tornado and this library around connections not being available.

**Comment by ploxiln** [comment]
I think we'll need a more specific and detailed complaint.

The typical/suggested strategy is to publish messages to localhost, not try to use nsqlookupd to find where to publish messages to. (That's for nsq consumers.)

The simplest way to publish messages is with the nsqd http publish endpoint. You can use any http client library you like. It's very simple.

It is possible to use an nsq library and the tcp-binary-protocol to publish messages, but it may be awkward or tricky depending on what you are trying to do.

**Comment by JackyXiong** [comment]
Need more detailed specific.

**Comment by Umesh-JNU** [comment]
Can anyone provide me the exact way of writing a message to nsq using pynsq? As the given example in the docs doesn't provide clear cur view of writing message.
