### ISSUE TITLE
Pynsq fails to send large messages when using Deflate / Snappy compression

### ISSUE THREAD

**Issue by SpaTmole** [nsqio/pynsq#207]
## The Problem:
During sending relatively big messages with one of the specified compression algorithms (deflate, snappy) server responds with Error (unexpected EOF).

## The cause:
When compression type is specified the connection is being upgraded with custom Socket classes, which have own `send` methods. In those send methods original socket had one attempt to send the whole pack of compressed data without validation of integrity. The custom `send` method returns the original length of uncompressed data despite the actual amount of sent bytes.
https://github.com/nsqio/pynsq/blob/v0.8.2/nsq/snappy_socket.py#L43
https://github.com/nsqio/pynsq/blob/v0.8.2/nsq/deflate_socket.py#L44

## Solution:
Remove compress-on-flight inside the `send` method - replace it with the original `socket.send`.
Add Encoder's classes which will compress with specified algorithms **before** sending data through the socket / `tornado.IOstream`.

**Comment by ploxiln** [comment]
Some projects like to always open an issue along with a pull-request, but we are not like that - if you have a problem and a fix, it can all live in a single pull-request.

closing this: addressed by #208

Thanks for figuring this out!
