### ISSUE TITLE
New beta release

### ISSUE THREAD

**Issue by aaronjheng** [nsqio/pynsq#233]
Could you guys make a beta release so we can test it easily.

**Comment by mreiferson** [comment]
Yea, I'll push one out.

**Comment by mreiferson** [comment]
https://pypi.org/project/pynsq/0.9.0b1/

**Comment by ploxiln** [comment]
can you push up a git tag?

**Comment by mreiferson** [comment]
I pushed one up, then realized we've never tagged any previous beta/alpha releases.... shrug

**Comment by ploxiln** [comment]
Thanks.

In case anyone is interested, this is how I sort of faked a beta release for pip (works in requirements.txt or in pip install command):

```
https://github.com/nsqio/pynsq/archive/48bf62d65ea6.tar.gz#egg=pynsq==0.9.0b1
```

**Comment by ploxiln** [comment]
(this "faked a beta release for pip" thing was only needed before the real beta release)
