### ISSUE TITLE
tornado.general:Connect error on fd 604: [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by typ431127** [nsqio/pynsq#235]
python3.7.2
```python
import nsq

def handler(message):
    print(message)
    return True

r = nsq.Reader(message_handler=handler,
        lookupd_http_addresses=['http://192.168.100.192:4161'],
        topic='duduniao', channel='duduniao', lookupd_poll_interval=15)
nsq.run()
```
**error**
```
WARNING:tornado.general:Connect error on fd 604: [Errno 11001] getaddrinfo failed
WARNING:tornado.general:Connect error on fd 604: [Errno 11001] getaddrinfo failed
WARNING:nsq.reader:[node2:4150:duduniao:duduniao] connection closed
WARNING:nsq.reader:[node2:4180:duduniao:duduniao] connection closed
```

**Comment by ploxiln** [comment]
nsqlookupd appears to have returned "node2" as the hostname of the nsqd instances that have that topic, and the nsq consumer (Reader) cannot resolve the hostname "node2". You can use the `--broadcast-address` option for nsqd to set a hostname to be reported to nsqlookupd (and then sent to readers), such that consumers can resolve that hostname correctly.

**Comment by typ431127** [comment]
I have solved this problem, I added the hosts resolution, thank you！
