### ISSUE TITLE
Troubled about Writer : Stream is closed

### ISSUE THREAD

**Issue by vMagina** [nsqio/pynsq#240]
When I use nsq to send msg to nsq next time , I encounter a problem.
My code is:
```
class NsqManger(object):
    def __init__(self, addr_list):
        self.nsq_producer = nsq.Writer(addr_list, name='o')
        self.io_loop = tornado.ioloop.IOLoop.instance()

    def producer(self, topic, message, callback=None):
        if not self.nsq_producer.conns:
            return self.io_loop.add_callback(
                partial(self.producer, *(topic, message, callback))
            )
        self.nsq_producer.pub(topic, message, callback)

    def on_finish(self, conn, status_code):
        print(conn, status_code)
        self.io_loop.stop()

    def pub(self, topic, message):
        self.reset()
        io_loop = tornado.ioloop.IOLoop.instance()
        io_loop.add_callback(
            partial(self.producer, *(topic, message, self.on_finish))
        )
        io_loop.start()

w = NsqManger('127.0.0.1:4152'])
w. pub('test', b'h') #first time ok
time.sleep(240)
w.pub('test', b'h') #second time , I encontered the problem
```

The problem is :

`WARNING:nsq.client:[127.0.0.1:4152:o] connection is stale (54022.00s), closing
127.0.0.1:4152 b'OK'
ERROR:nsq.client:[127.0.0.1:4152:o] ERROR: ConnectionClosedError('Stream is closed',)
127.0.0.1:4152 Stream is closed`

Why the callback is called twice and the statuses are diferent?
Can anyone provide me some explanations?

**Comment by ploxiln** [comment]
You used single-backticks to quote your code, but that only works on a single line. For multiple lines, you need to use triple-backticks, on their own lines, like this:

    ```
    this is your code
    on multiple lines
    ```

-------

The problem is `time.sleep(240)` and also the location of `io_loop.start()`. nsq has heartbeat messages (aka keep-alives) that need to be sent back and forth, and pynsq automatically sends them, but only if the tornado event loop is running. You need the `io_loop` to keep running the entire time, including while you are waiting to send another message. You can't use `time.sleep()`. It's a sort of complicated subject.

**Comment by ploxiln** [comment]
If you don't want to use tornado for your entire publishing application, then I suggest just using the http interface to publish messages, e.g. `POST http://127.0.0.1:4151/pub?topic=mytopic`, using whatever http client library you prefer.

**Comment by vMagina** [comment]
> You used single-backticks to quote your code, but that only works on a single line. For multiple lines, you need to use triple-backticks, on their own lines, like this:
> 
> ```
> ```
> this is your code
> on multiple lines
> ```
> ```
> 
> The problem is `time.sleep(240)` and also the location of `io_loop.start()`. nsq has heartbeat messages (aka keep-alives) that need to be sent back and forth, and pynsq automatically sends them, but only if the tornado event loop is running. You need the `io_loop` to keep running the entire time, including while you are waiting to send another message. You can't use `time.sleep()`. It's a sort of complicated subject.

Thanks a lot. So, I should not stop the `io_loop` and keep it running.

**Comment by ploxiln** [comment]
> So, I should not stop the io_loop and keep it running.

Yes, but note that `io_loop.start()` will not return while it is running. So that will need to be done outside the manager. For this example, perhaps something like:

```python
class NsqManger(object):
    def __init__(self, addr_list):
        self.nsq_producer = nsq.Writer(addr_list, name='o')

    def pub(self, topic, message):
        if not self.nsq_producer.conns:
            return tornado.ioloop.IOLoop.current().add_callback(
                partial(self.pub, topic, message)
            )
        self.nsq_producer.pub(topic, message, self.on_finish)

    def on_finish(self, conn, status_code):
        print(conn, status_code)


io_loop = tornado.ioloop.IOLoop.current()

def do_stuff():
    w = NsqManger(['127.0.0.1:4152'])
    w.pub('test', b'h')
    io_loop.call_later(240, w.pub, 'test', b'h')

io_loop.add_callback(do_stuff)
io_loop.start()  # will not return until io_loop is stopped ... which it generally should not be
```

> Does the nsqd server will release resources automatically when the connection is closed caused by the heartbeat?

yes, on the nsqd side
