### ISSUE TITLE
is_starved() return False when channel is empty

### ISSUE THREAD

**Issue by penfree** [nsqio/pynsq#242]
I meet a problem when batch process message.
1. max_in_flight is set to 256
2. from nsqadmin i can see:  depth=0, Memory + Disk = 0+0, In-Flight=35, Deferred=0, Requeued=0, Timed Out=2985， Connections=2

As I understand it， is_starved() will return True when channel is empty, but now reader.is_starved() return false

**Comment by mreiferson** [comment]
`is_starved` is entirely based on the client's state, e.g. its `RDY` and how many messages are in flight.

It looks like your issue is probably something to do with the `2985` timed out messages, if I had to guess.
