### ISSUE TITLE
Production release of 0.9.0

### ISSUE THREAD

**Issue by katzdm** [nsqio/pynsq#250]
We've been using `0.9.0b2` in production for several weeks now, and things look swell. I'd like to propose tagging and releasing a full `0.9.0` version.

<hr>

One "breaking change" might be worth noting, though it only affects cases that weren't legal to begin with. Consider the code:
```
@tornado.gen.coroutine
def message_handler(nsq_message):
    nsq_message.enable_async()
    ...  # Do some stuff

    def callback():
        nsq_message.finish()

    tornado.ioloop.IOLoop.current().add_future(some_fn(), callback)


if __name__ == '__main__':
    nsq.Reader(message_handler=message_handler, ...)
    nsq.run()
```

For `pynsq<0.9.0b2`, applications should never provide a coroutine as a `message_handler`. Doing so, however, would not usually fail - Instead, it induced a race between the message-handler invoking `nsq_message.enable_async()`, and the library checking whether async was enabled. This usually "worked", as long as the handler didn't `yield` before enabling async. Running the same with `pynsq==0.9.0b2`, however, typically results in a double-response for the message (since the library calls `_maybe_finish()` after `message_handler` yields a result).

I don't think this needs to be corrected, but it might be worth including in the release notes, since because [Hyrum's Law](https://www.hyrumslaw.com/). Something like

> Asynchronous message handlers can no longer respond to messages from coroutines outliving the handlers themselves. This was not legal before, but often worked accidentally.

Thanks for your time, and thanks for your work in maintaining this library!

**Comment by ploxiln** [comment]
That's a good point, thanks for mentioning it.

(Also, I think that any code after the first `yield` would never run, so it only worked for a `@coroutine` decorated function that never yielded anyway. And python-3.5+ `async def` would never run at all.)

**Comment by mreiferson** [comment]
I guess... I'll have to figure out how to do a release again?

**Comment by mreiferson** [comment]
https://github.com/nsqio/pynsq/releases/tag/v0.9.0
