### ISSUE TITLE
reader: potential memory leak

### ISSUE THREAD

**Issue by zouzhen** [nsqio/pynsq#251]
After I started nsq, even if I did nothing, I even disconnected from nsqd, but the memory leaks still exist. For example, if I start two processes, one in use and the other not in use, the memory difference between the two processes is 10 times, and the memory of the process that uses nsq still increases. From this I can determine that the memory leak is related to the client, but I am not sure, and I ask the author to give a reply. By the way, it is now running in the Docker environment.

**Comment by zouzhen** [comment]
The version I used is 0.9.0b1.

**Comment by jehiah** [comment]
@zouzhen can you provide example code that reproduces the situation you are seeing?

**Comment by ploxiln** [comment]
I have some services using pynsq-0.9.0b1, and pynsq-0.9.0b2, which have been running for over a month, without increase in memory usage after the first 12 hours or so. (One around 55 MiB RSS, another around 250 MiB RSS, both using more libraries and doing more work than just pynsq.) It is expected to take some memory to load in pynsq and the libraries it depends on. After that, it really depends on your application code, and on the python allocator (which varies by python version).

It is quite possible to use pynsq intensively, without experiencing memory "leaks" (unbounded memory growth). It is also possible that there is some corner-case where pynsq is responsible for never-recovered memory usage, but much more detail will be needed for anyone to figure what is happening in your case.

**Comment by zouzhen** [comment]
The following lists the process information that is displayed after I run the top command. The process information indicates that the virtual memory increases a lot. 
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
      1 root      20   0  349340  25500   5980 S   0.0  0.1   0:02.46 python3
    10 root      20   0 6248288  46560   3696 S   0.0  0.1   0:01.30 python3
Process 1 is the main process and does not use the nsq service. Therefore, no memory leakage occurs. Process 10 is a sub-process started by process 1 and uses the nsq service. The memory usage increases unbelievably. The lookupd_http_addresses method is used, and the nsqd method is used.Leakage occurs on both ARM and x86 servers.

**Comment by zouzhen** [comment]
import sys
import nsq
import ssl
# perform work
def handler_msg(payload):
    #obj = json.loads(payload.body)
    payload.enable_async()
    print(payload.body,payload.id)
    payload.finish()

if __name__ == '__main__':
    opts = {
        "cert_reqs": ssl.CERT_REQUIRED,
        "keyfile": "...",
        "certfile": "...",
        "ca_certs": "...",
    }
    nsq.Reader(message_handler=handler_msg,
               lookupd_http_addresses=["192.168.0.111:4161,192.168.0.111:4261"],
               topic="test",
               channel="test1",
               tls_v1=True,
               tls_options=opts,
               max_in_flight=10,
               max_tries=1,
               max_backoff_duration=sys.float_info.min)
    nsq.run()

**Comment by jehiah** [comment]
@zouzhen can you share code for what your handlers are doing? Can you describe what your process is doing with each message? It's likely memory usage is a result of how messages are being processed, not a result of the pynsq code.

**Comment by zouzhen** [comment]
import sys,nsq,ssl
def handler_msg(payload):
    payload.enble_async()
    print(payload.body,payload.id)
    payload.finished()

if __name__ == '__main__':
    opts = {
        "cer_reqs":ssl.CERT_REQUIRED,
        "keyfile":"/nsq/client-key.pem",
        "certfile":"/nsq/client-cert.pem",
        "ca_certs":"/nsq/ca-cert.pem"
    }
    nsq.Reader(
    message_handler = handler_msg,
    lookupd_http_addresses = ["192.168.0.111:4161,192.168.0.111:4261"]
    topic = "test",
    channel = "test1",
    tls_v1 = True,
    tls_options = opts,
    max_in_flight = 10,
    max_tries = 1,
    max_backoff_duration = sys.float_info.min
    )
    nsq.run()

**Comment by zouzhen** [comment]
import sys,nsq,ssl
def handler_msg(payload):
payload.enble_async()
print(payload.body,payload.id)
payload.finished()

if \__name\__ == '\__main\__':
opts = {
"cer_reqs":ssl.CERT_REQUIRED,
"keyfile":"/nsq/client-key.pem",
"certfile":"/nsq/client-cert.pem",
"ca_certs":"/nsq/ca-cert.pem"
}
nsq.Reader(
message_handler = handler_msg,
lookupd_http_addresses = ["192.168.0.111:4161,192.168.0.111:4261"]
topic = "test",
channel = "test1",
tls_v1 = True,
tls_options = opts,
max_in_flight = 10,
max_tries = 1,
max_backoff_duration = sys.float_info.min
)
nsq.run()

**Comment by zouzhen** [comment]
We ran a demo process in lookupd mode for a whole night. The virtual memory reached about 40 GB, but we did not process related services. To better locate the cause, the nsqd mode is used, but no memory leakage occurs. We compared the source code and found that the difference lies in whether tornado.httpclient is used. However, we have not located the cause yet and expect the author to provide a reply.

**Comment by ploxiln** [comment]
please use "fenced code blocks" when pasting code samples: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks (you can edit your existing comment to change the formatting)

It looks like this is not a working example, because `enble_async()` and `finished()` are typos:

```python
def handler_msg(payload):
    payload.enble_async()
    print(payload.body,payload.id)
    payload.finished()
```

I wonder if it is possible that some errors contacting nsqlookupd could cause a leak ... that's what I might try to look at first ...

Anyway, can you specify python version and tornado version you are using?

**Comment by zouzhen** [comment]
I'm sorry I didn't review the submitted code, but I'll make a correction. 
''' 
def handler_msg(payload):
    payload.enable_async()
    print(payload.id)
    payload.finish()
''' 
We just used memory_profile to check the memory leakage. After an hour, the problem did not occur on the x86 server.

**Comment by zouzhen** [comment]
I'm sorry I didn't review the submitted code, but I'll make a correction.
```
import sys,nsq,ssl
def handler_msg(payload):
    payload.enable_async()
    print(payload.id)
    payload.finish()

if _name_ == '_main_':
opts = {
"cer_reqs":ssl.CERT_REQUIRED,
"keyfile":"/nsq/client-key.pem",
"certfile":"/nsq/client-cert.pem",
"ca_certs":"/nsq/ca-cert.pem"
}
nsq.Reader(
message_handler = handler_msg,
lookupd_http_addresses = ["192.168.0.111:4161,192.168.0.111:4261"]
topic = "test",
channel = "test1",
tls_v1 = True,
tls_options = opts,
max_in_flight = 10,
max_tries = 1,
max_backoff_duration = sys.float_info.min
)
nsq.run()
```

**Comment by zouzhen** [comment]
I'm sorry I didn't review the submitted code, but I'll make a correction.
```python
import sys
import nsq
import ssl
from memory_profiler import profile
# perform work
def handler_msg(payload):
    payload.enable_async()
    print(payload.id)
    payload.finish()

@profile
def watch_nsq():
    opts = {
        "cert_reqs": ssl.CERT_REQUIRED,
        "keyfile": "/campusai/certs/nsq/client-key.pem",
        "certfile": "/campusai/certs/nsq/client-cert.pem",
        "ca_certs": "/campusai/certs/nsq/ca-cert.pem",
    }
    nsq.Reader(message_handler=handler_msg,
               lookupd_http_addresses=["10.77.134.33:4161","10.77.134.33:4261"],
               topic="crowdcount_dis",
               channel="test1",
               tls_v1=True,
               tls_options=opts,
               max_in_flight=10,
               max_tries=1,
               max_backoff_duration=sys.float_info.min)

    nsq.run()

if __name__ == '__main__':
    watch_nsq()
```

**Comment by zouzhen** [comment]
I'm sorry I didn't review the submitted code, but I'll make a correction.
```python
import sys
import nsq
import ssl
from memory_profiler import profile
# perform work
def handler_msg(payload):
    payload.enable_async()
    print(payload.id)
    payload.finish()

@profile
def watch_nsq():
    opts = {
        "cert_reqs": ssl.CERT_REQUIRED,
        "keyfile": "/nsq/client-key.pem",
        "certfile": "/nsq/client-cert.pem",
        "ca_certs": "/nsq/ca-cert.pem",
    }
    nsq.Reader(message_handler=handler_msg,
               lookupd_http_addresses=["192.168.0.101:4161","192.168.0.101:4261"],
               topic="crowdcount_dis",
               channel="test1",
               tls_v1=True,
               tls_options=opts,
               max_in_flight=10,
               max_tries=1,
               max_backoff_duration=sys.float_info.min)

    nsq.run()

if __name__ == '__main__':
    watch_nsq()
```
The memory leakage check is added. After the test is performed on the ARM for about two hours, the memory increases by 11 MB, but the virtual memory increases a lot. The change of the virtual memory is not the change of the actual memory. Is it because of the system architecture?

**Comment by zouzhen** [comment]
I'm sorry I didn't review the submitted code, but I'll make a correction.
```python
import sys
import nsq
import ssl
from memory_profiler import profile
# perform work
def handler_msg(payload):
    payload.enable_async()
    print(payload.id)
    payload.finish()

@profile
def watch_nsq():
    opts = {
        "cert_reqs": ssl.CERT_REQUIRED,
        "keyfile": "/nsq/client-key.pem",
        "certfile": "/nsq/client-cert.pem",
        "ca_certs": "/nsq/ca-cert.pem",
    }
    nsq.Reader(message_handler=handler_msg,
               lookupd_http_addresses=["192.168.0.101:4161","192.168.0.101:4261"],
               topic="test",
               channel="test1",
               tls_v1=True,
               tls_options=opts,
               max_in_flight=10,
               max_tries=1,
               max_backoff_duration=sys.float_info.min)

    nsq.run()

if __name__ == '__main__':
    watch_nsq()
```
The memory leakage check is added. After the test is performed on the ARM for about two hours, the memory increases by 11 MB, but the virtual memory increases a lot. The change of the virtual memory is not the change of the actual memory. Is it because of the system architecture?

**Comment by zouzhen** [comment]
I'm sorry I didn't review the submitted code, but I'll make a correction.
```python
import sys
import nsq
import ssl
from memory_profiler import profile
# perform work
def handler_msg(payload):
    payload.enable_async()
    print(payload.id)
    payload.finish()

@profile
def watch_nsq():
    opts = {
        "cert_reqs": ssl.CERT_REQUIRED,
        "keyfile": "/nsq/client-key.pem",
        "certfile": "/nsq/client-cert.pem",
        "ca_certs": "/nsq/ca-cert.pem",
    }
    nsq.Reader(message_handler=handler_msg,
               lookupd_http_addresses=["192.168.0.101:4161","192.168.0.101:4261"],
               topic="test",
               channel="test1",
               tls_v1=True,
               tls_options=opts,
               max_in_flight=10,
               max_tries=1,
               max_backoff_duration=sys.float_info.min)

    nsq.run()

if __name__ == '__main__':
    watch_nsq()
```
The memory leakage check is added. After the test is performed on the ARM for about two hours, the memory increases by 11 MB, but the virtual memory increases a lot. The change of the virtual memory is not the change of the actual memory. Is it because of the system architecture?
```
python:3.7.3
tornado:5.1.1
```

**Comment by mreiferson** [comment]
One other debugging point, would it be possible to test against previous stable releases of `pynsq` (which would necessarily depend on earlier versions of Tornado)?

**Comment by zouzhen** [comment]
Thank you very much. I have used the following software version and no memory leakage occurs:
```
python:3.7.3
pynsq:0.9.0b1
tornado:4.5.3
```

**Comment by zouzhen** [comment]
Thank you very much, using the following versions of software, there is no memory leakage again
```
python:3.7.3
pynsq:0.9.0b1
tornado:4.5.3
```
