### ISSUE TITLE
reader: connection initialization doesn't respect max-in-flight constraint

### ISSUE THREAD

**Issue by alpaker** [nsqio/pynsq#252]
`Reader._on_connection_ready()` initializes a connection's RDY state in the following block:
```
        # we send an initial RDY of 1 up to our configured max_in_flight
        # this resolves two cases:
        #    1. `max_in_flight >= num_conns` ensuring that no connections are ever
        #       *initially* starved since redistribute won't apply
        #    2. `max_in_flight < num_conns` ensuring that we never exceed max_in_flight
        #       and rely on the fact that redistribute will handle balancing RDY across conns
        if not self.backoff_timer.get_interval() or len(self.conns) == 1:
            # only send RDY 1 if we're not in backoff (some other conn
            # should be testing the waters)
            # (but always send it if we're the first)
            self._send_rdy(conn, 1)
```
There doesn't seem to anything here that corresponds to point 2 in the comment, that is, no guarantee that sending RDY 1 on the new connection won't take the total RDY count past the configured `max_in_flight`.  But if `max_in_flight` is less than the connection count, sending RDY 1 on every new connection can do that: If a new reader connects to `n` servers there will be a brief window in which the total RDY count will be `n`, even if `max_in_flight < n`. The window of overcommitment is short—it'll be fixed as a side effect of RDY redistribution—but it's long enough that it can lead to undesirable results (e.g., we recently had an issue with a video transcoder grabbing too many tasks on startup and OOMing shortly thereafter as a result).

**Comment by mreiferson** [comment]
see #254
