### ISSUE TITLE
pynsq does not reconnect to nsqd automatically in some case

### ISSUE THREAD

**Issue by yangjin-unique** [nsqio/pynsq#264]
Reproduce steps on centos 7.2:
1) Change system time to sometime in the future.
2) Then change time back.
3) Restart nsqd (since change of system time has bad affects on nsqd).
4) Now we found pynsq did not reconnect to nsqd automatically. We had to restart service to workaroud.
This case shoud be rarely happened :). We also have some golang services that using go-nsq coud handle this case correctly (reconnect automatically without restart).

I found the following code in _connect_to_nsqd_ that prevents this reconnection as system time changes.
`if last_connect_attempt and last_connect_attempt > now - 10:
            return`

I am not sure if it is a problem. Is there a better way to deal with this case? 
Thanks.

**Comment by mreiferson** [comment]
Thanks for the report.

We've generally written NSQ (server and clients) with the expectation that there's stability w/r/t time in the operating environment, e.g. by running `ntpd`.

There's likely a way to use monotonic clocks here, but I'm not sure it's worth the effort.
